global using System;
global using System.Text;
global using HRDomain.CustomConverter;
global using AutoMapper;
global using HRDomain.Services;
global using HRService;
global using HRDomain.Entities;
global using HRRepository.Data;
global using System.Globalization;
global using System.ComponentModel.DataAnnotations;

global using HRDomain.Specification;
global using HRRepository;
global using HRSystem.DTO;
global using HRSystem.Error_Handling;
global using HRSystem.Helpers;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using System.Linq.Expressions;
